version: '3'
services:
  qilletni-db:
    image: postgres
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: qilletni
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: qilletni
    volumes:
      - qilletni-database:/var/lib/postgresql/data

  qilletni:
    build:
      context: docker/
    depends_on:
      - qilletni-db
    volumes:
      - .:/workspace
      - qilletni-packages:/root/.qilletni/packages
    profiles:
      - cli

volumes:
  qilletni-database:
  qilletni-packages:
