name: Publish qilletni/spotify

on:
  workflow_dispatch: # For snapshot versions
  push:
    tags:
      - 'spotify-v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/qilletni/qilletni:snapshot

    steps:
      - uses: actions/checkout@v6

      - name: Set up Java 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'adopt'
          cache: 'gradle'

      - uses: gradle/actions/setup-gradle@v5

      - name: Build Package
        run: qilletni build -v
        working-directory: qilletni-spotify

      - name: QPM Publish
        run: qpm publish
        working-directory: qilletni-spotify
        env:
          QPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.DISPATCH_PAT }}
          repository: Qilletni/qilletni-package-docs
          event-type: update-docs
          client-payload: '{"package": "spotify"}'
